name: Deploy to GitHub Pages and deliver to DockerHub
on:
  release:
    types: [published]
jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Build app
        run: flutter build web --target=lib/local_main.dart --base-href /populare/
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: build/web
      - name: Update GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
