name: Run linting and tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Format
        run: flutter format --set-exit-if-changed .
      - name: Generate mocks
        run: flutter pub run build_runner build
      - name: Lint
        run: flutter analyze
      - name: Test
        run: flutter test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        run: |
          echo "POPULARE_BUILD_VERSION=$(python get_app_version.py)" >> $GITHUB_ENV
      - name: Check version
        run: |
          echo POPULARE_BUILD_VERSION
          echo ${{ env.POPULARE_BUILD_VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker, online
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: kostaleonard/populare:latest,kostaleonard/populare:${{ env.POPULARE_BUILD_VERSION }}
      - name: Build and export to Docker, offline
        uses: docker/build-push-action@v3
        with:
          load: true
          build-args: APP_TARGET=lib/local_main.dart
          tags: kostaleonard/populare-offline:latest,kostaleonard/populare-offline:${{ env.POPULARE_BUILD_VERSION }}
  trivy-scan:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}
  deliver:
    needs: [trivy-scan]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      # TODO I think this builds again, doesn't cache
      # These build steps use the cached images according to docker/build-push-action docs.
      # We want to use the cached images so that we don't build twice.
      - name: Build and push, online
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kostaleonard/populare:latest,kostaleonard/populare:${{ env.POPULARE_BUILD_VERSION }}
      - name: Build and push, offline
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: APP_TARGET=lib/local_main.dart
          tags: kostaleonard/populare-offline:latest,kostaleonard/populare-offline:${{ env.POPULARE_BUILD_VERSION }}
